### ISSUE TITLE
Commands referring to 'clients' group fail with Chef 12.9.41

### ISSUE THREAD

**Issue by dannypurcell** [chef/knife-acl#35]
I came across this while following some [advice on pre-creating nodes](https://github.com/chef/chef-server/issues/63).
As an example, the following command from the README claims the 'clients' group does not exist although it is clearly in the group list.

```

$ date;knife --version;chef gem list knife-acl;echo "*** Groups *** "; knife group list | grep clients; knife acl add group clients containers nodes create,read
Thu May  5 15:08:49 CDT 2016
Chef: 12.9.41

*** LOCAL GEMS ***

knife-acl (1.0.2)
*** Groups ***
clients
FATAL: group 'clients' does not exist
```

**Comment by xakraz** [comment]
@dannypurcell : Sometime you get this error message when you don't have enough permissions on the chef-server node...

**Comment by tas50** [comment]
Closing based on @xakraz's comments
