### ISSUE TITLE
Cant add client to node

### ISSUE THREAD

**Issue by voroniys** [chef/knife-acl#43]
knife acl show clients mynode - shows some output, so client exists

knife acl show nodess mynode - shows some output, so the node  exists as well

But when I try:
knife acl add client mynode nodes mynode create,read,update,delete,grant
Adding 'mynode' to 'create' ACE of 'mynode'
ERROR: The data in your request was invalid
Response: The client(s) 'mynode' do not exist in this organization.

**Comment by stevendanna** [comment]
@voroniys Which version of Chef Server is this against? Also, is `mynode` the actual client and node name?  If not, might you be hitting this bug: https://github.com/chef/chef-server/pull/1275 which is fixed in the latest Chef Server.

**Comment by voroniys** [comment]
Looks like it the the mentioned bug. I've replaced the hostname which had dots in it.
Issue can be closed then
